CREATE TABLE "Problem" (
    "problem_id" INT PRIMARY KEY,
    "title" VARCHAR(100) NOT NULL,
    "statement" TEXT NOT NULL,
    "difficulty" VARCHAR(10) CHECK ("difficulty" IN ('Easy', 'Medium', 'Hard')) NOT NULL,
    "time_limit" INT NOT NULL, -- in milliseconds
    "memory_limit" INT NOT NULL, -- in MB
    "created_by" INT,
    FOREIGN KEY ("created_by") REFERENCES "User" ("user_id") ON DELETE SET NULL
);

INSERT INTO "Problem" ("problem_id", "title", "statement", "difficulty", "time_limit", "memory_limit", "created_by") VALUES
(1, 'Two Sum', 'Given an array of integers, return indices of the two numbers that add up to a target.', 'Easy', 1000, 256, 6),
(2, 'Valid Parentheses', 'Determine if the input string containing brackets is structurally sound.', 'Easy', 1000, 256, 7),
(3, 'Merge Sorted Arrays', 'Merge two sorted arrays into one single sorted array structure.', 'Easy', 1000, 256, 8),
(4, 'Palindrome Number', 'Determine whether an integer reads the same forward and backward.', 'Easy', 500, 128, 6),
(5, 'Reverse Linked List', 'Invert the sequential pointer directions of a singly linked list.', 'Easy', 1000, 256, 10),
(6, 'FizzBuzz Ultimate', 'Generate string arrays switching multiples of 3 and 5 with word tokens.', 'Easy', 500, 64, 11),
(7, 'Binary Search Baseline', 'Find the exact insertion index of a target value within a sorted array.', 'Easy', 1000, 256, 12),
(8, 'Single Number Locator', 'Find the unique element in an array where every other element repeats twice.', 'Easy', 1000, 256, 13),
(9, 'Valid Anagram', 'Check if string s can be rearranged directly into string t.', 'Easy', 800, 128, 14),
(10, 'Maximum Subarray Sum', 'Find the contiguous subarray which has the largest sum using Kadanes.', 'Easy', 1000, 256, 6),
(11, 'Climbing Stairs', 'Find the unique combination counts to reach the top of a staircase.', 'Easy', 500, 64, 7),
(12, 'Invert Binary Tree', 'Flip a binary tree so its left child becomes its right child mirror.', 'Easy', 1000, 256, 8),
(13, 'Contains Duplicate', 'Return true if any value appears at least twice inside the sequence.', 'Easy', 1200, 256, 15),
(14, 'Length of Last Word', 'Return the length of the final word found within a spaced string.', 'Easy', 400, 64, 10),
(15, 'Pascal Triangle Generator', 'Compute the first N rows of coefficients mimicking dynamic binomial sums.', 'Easy', 1000, 128, 11),
(16, 'Knapsack 0/1 Problem', 'Maximize total weight values inside bounded structural capacities.', 'Medium', 1500, 256, 6),
(17, 'Longest Common Subsequence', 'Find the maximum subsequence span shared between two text strings.', 'Medium', 2000, 256, 7),
(18, 'XOR Permutations', 'Evaluate array operations minimizing sequential item bitwise differences.', 'Medium', 2000, 512, 8),
(19, '3Sum Zero Tracker', 'Find all unique triplets in an array that sum up to exactly zero.', 'Medium', 1500, 256, 12),
(20, 'Container With Most Water', 'Find two lines that form a container holding the maximum water.', 'Medium', 1000, 256, 13),
(21, 'Longest Substring Without Repeating', 'Find the length of the longest substring without repeating characters.', 'Medium', 1500, 256, 14),
(22, 'Group Anagrams Together', 'Given an array of strings, group all structural anagrams together.', 'Medium', 1800, 256, 15),
(23, 'Product of Array Except Self', 'Return an array where each element equals the product of all others without dividing.', 'Medium', 1000, 512, 6),
(24, 'Coin Change Optimization', 'Compute the fewest number of coins needed to make up a target amount.', 'Medium', 1200, 256, 7),
(25, 'Course Schedule DFS', 'Determine if courses can be finished matching directed graph dependencies.', 'Medium', 2000, 512, 8),
(26, 'Pacific Atlantic Water Flow', 'Find grid coordinate blocks discharging fluids seamlessly into oceans.', 'Medium', 2500, 256, 10),
(27, 'Palindromic Substrings Count', 'Count the total number of individual palindromic substrings inside text s.', 'Medium', 1000, 256, 11),
(28, 'Rotated Sorted Array Search', 'Locate target values inside sorted arrays shifted by arbitrary offsets.', 'Medium', 1000, 256, 12),
(29, 'Validate Binary Search Tree', 'Confirm if a given binary tree matches strict binary tree properties.', 'Medium', 1200, 256, 13),
(30, 'Number of Islands', 'Count distinct islands inside an isolated grid mapped by 1s and 0s.', 'Medium', 2000, 256, 14),
(31, 'Top K Frequent Elements', 'Extract the top K items matching highest recurring frequencies from an array.', 'Medium', 1500, 256, 15),
(32, 'House Robber Stashes', 'Maximize stolen yields along a row of houses without triggering adjacent alarms.', 'Medium', 1000, 128, 6),
(33, 'Edit Distance Engine', 'Compute the minimum operations needed to convert string word1 to word2.', 'Hard', 2000, 512, 8),
(34, 'Segment Tree Bounds Update', 'Efficiently modify array range segments while processing query blocks.', 'Hard', 2500, 512, 11),
(35, 'Median of Two Sorted Arrays', 'Find the consolidated median value of two sorted arrays in logarithmic time.', 'Hard', 1500, 256, 7),
(36, 'Regular Expression Matching', 'Implement regex matching with support for dot metrics and star modifiers.', 'Hard', 2000, 256, 12),
(37, 'Merge K Sorted Lists', 'Merge K sorted linked lists into one consolidated sorted linear structure.', 'Hard', 2500, 512, 13),
(38, 'Trapping Rain Water', 'Compute how much water a post-elevation landscape structure can trap after raining.', 'Hard', 1500, 256, 14),
(39, 'Sliding Window Maximum', 'Track maximum integer entities inside sliding subset vectors.', 'Hard', 2000, 512, 15),
(40, 'N-Queens Placement Matrix', 'Place N non-attacking chess queens safely across an N by N board layout.', 'Hard', 3000, 256, 6),
(41, 'Valid Palindrome II', 'Determine if a string can become a palindrome after deleting at most one character.', 'Easy', 800, 128, 6),
(42, 'Kth Largest Element', 'Find the Kth largest element in an unsorted array without fully sorting it.', 'Medium', 1500, 256, 7),
(43, 'Network Delay Time', 'Calculate the minimum time it takes for all nodes to receive a signal in a graph.', 'Medium', 2000, 512, 11),
(44, 'Binary Tree Maximum Path Sum', 'Find the maximum path sum of any non-empty path in a binary tree.', 'Hard', 1500, 256, 13),
(45, 'Subarray Sum Equals K', 'Given an array of integers, find the total number of continuous subarrays whose sum equals k.', 'Medium', 1500, 256, 6),
(46, 'Word Search Grid', 'Determine if a target string word exists sequentially within a 2D character grid matrix.', 'Medium', 2000, 256, 7),
(47, 'Longest Palindromic Substring', 'Find the longest contiguous palindromic substring within a given string s.', 'Medium', 1000, 256, 8),
(48, 'Binary Tree Zigzag Traversal', 'Return the zigzag level order traversal of a binary tree structural layout nodes.', 'Medium', 1000, 256, 10),
(49, 'K Closest Points to Origin', 'Find the K closest coordinate points to the planar origin (0, 0) using Euclidean distance.', 'Medium', 1200, 256, 11),
(50, 'Minimum Window Substring', 'Find the minimum window substring in s that contains all characters of string t.', 'Hard', 2500, 512, 12),
(51, 'Word Ladder Transformation', 'Find the length of the shortest transformation sequence from a begin word to an end word.', 'Hard', 3000, 512, 13),
(52, 'Remove Invalid Parentheses', 'Remove the minimum number of invalid parentheses to make the input string valid.', 'Hard', 2000, 256, 14),
(53, 'Fibonacci Sequence Base', 'Compute the N-th Fibonacci numerical element using basic dynamic storage paths.', 'Easy', 500, 64, 6),
(54, 'Valid Palindrome Baseline', 'Verify if a string reads identically backwards after removing non-alphanumeric text.', 'Easy', 500, 64, 7);